#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

const FRONTEND = path.join(
    ROOT,
    "frontend"
);

const GENERATED = path.join(
    ROOT,
    "esp8266",
    "generated"
);

const FILES = [

    {
        source: path.join(
            FRONTEND,
            "index.html"
        ),
        output: "index_html.h",
        variable: "INDEX_HTML"
    },

    {
        source: path.join(
            FRONTEND,
            "css",
            "styles.css"
        ),
        output: "style_css.h",
        variable: "STYLE_CSS"
    },

    {
        source: path.join(
            FRONTEND,
            "js",
            "app.js"
        ),
        output: "app_js.h",
        variable: "APP_JS"
    },

    {
        source: path.join(
            FRONTEND,
            "js",
            "controller.js"
        ),
        output: "controller_js.h",
        variable: "CONTROLLER_JS"
    },

    {
        source: path.join(
            FRONTEND,
            "js",
            "websocket.js"
        ),
        output: "websocket_js.h",
        variable: "WEBSOCKET_JS"
    }

];

function ensureDirectory(directory) {

    if (!fs.existsSync(directory)) {

        fs.mkdirSync(

            directory,

            {
                recursive: true
            }

        );

    }

}

function buildHeader(source, destination, variable) {

    if (!fs.existsSync(source)) {

        throw new Error(
            `Source file not found:\n${source}`
        );

    }

    const content = fs.readFileSync(
        source,
        "utf8"
    );

    const header = `#pragma once

// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
//
// Source:
// ${path.relative(ROOT, source)}
//
// Generated by:
// scripts/build-web.js
//
// DO NOT EDIT MANUALLY.
// -----------------------------------------------------------------------------

static const char ${variable}[] PROGMEM = R"rawliteral(
${content}
)rawliteral";

`;

    fs.writeFileSync(

        destination,

        header,

        "utf8"

    );

    console.log(
        `✓ ${path.relative(ROOT, destination)}`
    );

}

function main() {

    console.log("");

    console.log(
        "Generating web assets..."
    );

    ensureDirectory(
        GENERATED
    );

    for (const file of FILES) {

        buildHeader(

            file.source,

            path.join(
                GENERATED,
                file.output
            ),

            file.variable

        );

    }

    console.log("");

    console.log("Done.");

}

main();
